home/urls.py
from django.urls import path, include

from home import views

urlpatterns = [
    path("", views.index, name='home'),

]

product/urls.py
from django.urls import path

from product import views

urlpatterns = [
    path("category/", views.all_categories, name='category.all'),
    path("seller/", views.all_sellers, name='seller.all'),
    path("seller/<int:pk>/add_payment", views.add_seller_payment, name='seller.add_payment'),
    path("worker/", views.all_workers, name='worker.all'),
    path("box/", views.daily_box, name='box.daily'),
    path("quantity_types/", views.all_quantity_types, name='quantity_type.all'),
    path("currency/", views.all_currencies, name='currency.all'),
    path("material/", views.all_materials, name='material.all'),
    path("invoice/add", views.add_invoice, name='invoice.add'),
    path("invoice/<int:pk>/", views.view_invoice, name='invoice.view'),
    path("invoice/seller/<int:pk>/", views.seller_invoices, name='invoice.seller.view'),
    path("invoice/last", views.view_invoice_last, name='invoice.view.last'),
    path("invoice/all", views.all_invoices, name='invoice.all'),
    path("product/add/", views.add_product, name='product.add'),
    path("product/<int:pk>/edit", views.edit_product, name='product.edit'),
    path("product/autocomplete/", views.product_autocomplete, name='product.autocomplete'),
    path("product/get_currencies/", views.get_currencies, name='product.get_currencies'),
    path("product/get_sellers/", views.get_sellers, name='product.get_sellers'),
    path("product/get_workers/", views.get_workers, name='product.get_workers'),
    path("product/get_quantity_types/", views.get_quantity_types, name='product.get_quantity_types'),
    path("", views.all_products, name='product.all'),
    path("report/", views.reports_index, name='report.index'),

]

turbo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("product.urls")),
    path('users/', include("users.urls")),
    # path('', include("home.urls")),
]

untitled/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include("product.urls")),
    path('users/', include("users.urls")),
    path('', include("home.urls")),
]

product/models.py
from django.db import models


class Material(models.Model):
    name = models.CharField(max_length=100, unique=True)
    desc = models.CharField(max_length=200, null=True, blank=False)

    def __str__(self):
        return self.name


class QuantityType(models.Model):
    name = models.CharField(max_length=100, unique=True)
    value = models.FloatField()

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=100, unique=True)
    value = models.FloatField()
    rate = models.FloatField()

    def __str__(self):
        return self.name


class Category(models.Model):
    STATUS = Choices('Super', 'Regular')
    name = models.CharField(max_length=100, unique=True)
    desc = models.CharField(max_length=200, null=True, blank=False, default=None)
    type = models.CharField(max_length=100, choices=STATUS, default=STATUS.Regular)

    def __str__(self):
        return self.name


class Seller(models.Model):
    name = models.CharField(max_length=100, unique=True)
    phone = models.CharField(max_length=200, null=True, unique=True, blank=False)
    address = models.CharField(max_length=200, null=True, blank=False)

    def __str__(self):
        return self.name


class Worker(models.Model):
    name = models.CharField(max_length=100, unique=True)
    phone = models.CharField(max_length=200, null=True, unique=True, blank=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Weight(models.TextChoices):
        KG = '1', "KG"
        LITER = '2', "Liter"

    name = models.CharField(max_length=100, unique=True)
    stock_price = models.FloatField()
    price = models.FloatField()
    special = models.FloatField()
    expire = models.DateField(null=True, blank=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True)
    material = models.ManyToManyField(Material)
    quantity_type = models.ForeignKey(QuantityType, on_delete=models.SET_NULL, null=True)
    quantity = models.FloatField()
    weight = models.CharField(max_length=100, choices=Weight,default="1")
    extra_quantity = models.FloatField(null=True, default=0)
    barcode = models.CharField(null=True, max_length=100, blank=False, default=" ")
    identifier = models.CharField(null=True, max_length=100, blank=False)
    location = models.CharField(null=True, max_length=100, blank=False)
    alert_if_lower_than = models.IntegerField(null=True)
    image = models.CharField(max_length=100, blank=False, null=True)

    def __str__(self):
        return self.name


class Invoice(models.Model):
    total = models.FloatField()
    discount = models.FloatField()
    payed = models.FloatField()
    expected_earn = models.FloatField(blank=True, null=True)
    earn = models.FloatField(blank=True, null=True)
    dept = models.FloatField()
    date_published = models.DateTimeField(auto_now_add=True)
    currency = models.ForeignKey(Currency, on_delete=models.SET_NULL, null=True)
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True)
    worker = models.ForeignKey(Worker, on_delete=models.SET_NULL, null=True)
    paydate = models.DateField()


class InvoiceProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, )
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE, )
    quantity = models.FloatField()
    extra_quantity = models.FloatField()
    quantity_type = models.ForeignKey(QuantityType, on_delete=models.CASCADE, )
    piece_price = models.FloatField()
    total = models.FloatField()


class InvoicePayment(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE, )
    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, )
    add_date = models.DateTimeField(auto_now_add=True)
    amount = models.FloatField()


class DailyBoxOperation(models.Model):
    class Month(models.TextChoices):
        ADD = '1', "Add"
        TAKE = '2', "Take"

    currency = models.ForeignKey(Currency, on_delete=models.CASCADE, )
    amount = models.FloatField()
    operation = models.CharField(choices=Month.choices, max_length=5)
    reason = models.CharField(max_length=255, )
    add_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

product/forms.py
from django.forms import ModelForm

from product.models import *


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class SellerForm(ModelForm):
    class Meta:
        model = Seller
        fields = "__all__"


class InvoicePaymentForm(ModelForm):
    class Meta:
        model = InvoicePayment
        fields = "__all__"


# class DailyBoxOperationForm(ModelForm):
#     class Meta:
#         model = DailyBoxOperation
#         fields = "__all__"


class WorkerForm(ModelForm):
    class Meta:
        model = Worker
        fields = "__all__"


class CurrencyForm(ModelForm):
    class Meta:
        model = Currency
        fields = "__all__"


class QuantityTypeForm(ModelForm):
    class Meta:
        model = QuantityType
        fields = "__all__"


class MaterialForm(ModelForm):
    class Meta:
        model = Material
        fields = "__all__"


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = "__all__"

product/views.py
import datetime
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.core.paginator import PageNotAnInteger, Paginator, EmptyPage
from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from product.forms import *
from product.models import *
from turbo.settings import LOGIN_URL


# Categories
@login_required(login_url=LOGIN_URL)
def all_categories(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        method = request.POST.get("method").lower()
        if method == "post":
            form = CategoryForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Category added successfully.')
                return redirect("category.all")
        elif method == "delete":
            category_id = request.POST.get("category_id")
            Category.objects.get(pk=category_id).delete()
            messages.add_message(request, messages.WARNING, 'Category deleted successfully.')
            return redirect("category.all")
        elif method == "put":
            category_id = request.POST.get("category_id")
            category_name = request.POST.get("name")
            category_desc = request.POST.get("desc")
            category_exists = Category.objects.filter(name=category_name).exclude(pk=category_id)
            if not category_exists:
                category = Category.objects.get(pk=category_id)
                category.name = category_name
                category.desc = category_desc
                category.save()
                messages.add_message(request, messages.SUCCESS, 'Category updated successfully.')
            else:
                messages.add_message(request, messages.WARNING, 'Category data exists')

            return redirect("category.all")
            # Get method
    else:
        form = CategoryForm()
    categories = Category.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(categories, 15)
    try:
        categories = paginator.page(page)
    except PageNotAnInteger:
        categories = paginator.page(1)
    except EmptyPage:
        categories = paginator.page(paginator.num_pages)

    return render(request, 'category/all.html', {'categories': categories, "form": form})


# Sellers
@login_required(login_url=LOGIN_URL)
def all_sellers(request):
    # post method
    if request.method == 'POST':
        method = request.POST.get("method").lower()
        if method == "post":
            form = SellerForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Seller added successfully.')
                return redirect("seller.all")
        elif method == "delete":
            seller_id = request.POST.get("seller_id")
            Seller.objects.get(pk=seller_id).delete()
            messages.add_message(request, messages.WARNING, 'Seller deleted successfully.')
            return redirect("seller.all")
        elif method == "put":
            seller_id = request.POST.get("seller_id")
            seller_name = request.POST.get("name")
            seller_phone = request.POST.get("phone")
            seller_address = request.POST.get("address")
            seller_exists = Seller.objects.filter(name=seller_name).exclude(pk=seller_id)
            if not seller_exists:
                seller = Seller.objects.get(pk=seller_id)
                seller.name = seller_name
                seller.phone = seller_phone
                seller.address = seller_address
                seller.save()
                messages.add_message(request, messages.SUCCESS, 'Seller updated successfully.')
            else:
                messages.add_message(request, messages.WARNING, 'Seller data exists')

            return redirect("seller.all")
    # Get method
    else:
        form = SellerForm()
    sellers = Seller.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(sellers, 15)
    try:
        sellers = paginator.page(page)
    except PageNotAnInteger:
        sellers = paginator.page(1)
    except EmptyPage:
        sellers = paginator.page(paginator.num_pages)

    return render(request, 'seller/all.html', {'sellers': sellers, "form": form})


@login_required(login_url=LOGIN_URL)
def add_seller_payment(request, pk):
    form = InvoicePaymentForm(request.POST or None)
    if form.is_valid():
        form.save()
    invoices = Invoice.objects.filter(seller_id=pk)
    payments = InvoicePayment.objects.filter(seller_id=pk)
    seller = Seller.objects.get(pk=pk)
    return render(request, "seller/add_payment.html",
                  {"form": form, "invoices": invoices, "payments": payments, "seller": seller})


@login_required(login_url=LOGIN_URL)
def daily_box(request):
    # form = DailyBoxOperationForm(request.POST or None)
    # if form.is_valid():
    #     form.save()
    # today_min = datetime.datetime.combine(datetime.date.today(), datetime.time.min)
    # today_max = datetime.datetime.combine(datetime.date.today(), datetime.time.max)
    # ops = DailyBoxOperation.objects.filter(add_date__range=(today_min, today_max))
    # return render(request, "box/daily_box.html",
    #               {"form": form, "ops": ops})
    pass


# Workers
@login_required(login_url=LOGIN_URL)
def all_workers(request):
    # post method
    if request.method == 'POST':
        method = request.POST.get("method").lower()
        if method == "post":
            form = WorkerForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Worker added successfully.')
                return redirect("worker.all")
        elif method == "delete":
            worker_id = request.POST.get("worker_id")
            Worker.objects.get(pk=worker_id).delete()
            messages.add_message(request, messages.WARNING, 'Worker deleted successfully.')
            return redirect("worker.all")
        elif method == "put":
            worker_id = request.POST.get("worker_id")
            worker_name = request.POST.get("name")
            worker_phone = request.POST.get("phone")
            worker_exists = Worker.objects.filter(name=worker_name).exclude(pk=worker_id)
            if not worker_exists:
                worker = Worker.objects.get(pk=worker_id)
                worker.name = worker_name
                worker.phone = worker_phone
                worker.save()
                messages.add_message(request, messages.SUCCESS, 'Worker updated successfully.')
            else:
                messages.add_message(request, messages.WARNING, 'Worker data exists')

            return redirect("worker.all")
    # Get method
    else:
        form = WorkerForm()
    workers = Worker.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(workers, 15)
    try:
        workers = paginator.page(page)
    except PageNotAnInteger:
        workers = paginator.page(1)
    except EmptyPage:
        workers = paginator.page(paginator.num_pages)

    return render(request, 'worker/all.html', {'workers': workers, "form": form})


@login_required(login_url=LOGIN_URL)
def all_quantity_types(request):
    if request.method == 'POST':
        method = request.POST.get("method").lower()
        if method == "post":
            form = QuantityTypeForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.SUCCESS, 'Quantity Type added successfully.')
                return redirect("quantity_type.all")
        elif method == "delete":
            quantity_type_id = request.POST.get("quantity_type_id")
            QuantityType.objects.get(pk=quantity_type_id).delete()
            messages.add_message(request, messages.WARNING, 'Quantity Type deleted successfully.')
            return redirect("quantity_type.all")
        elif method == "put":
            quantity_type_id = request.POST.get("quantity_type_id")
            quantity_type_name = request.POST.get("name")
            quantity_type_value = request.POST.get("value")
            quantity_type_exists = QuantityType.objects.filter(name=quantity_type_name).exclude(pk=quantity_type_id)
            if not quantity_type_exists:
                quantity_type = QuantityType.objects.get(pk=quantity_type_id)
                quantity_type.name = quantity_type_name
                quantity_type.value = quantity_type_value
                quantity_type.save()
                messages.add_message(request, messages.SUCCESS, 'Quantity Type updated successfully.')
            else:
                messages.add_message(request, messages.WARNING, 'Quantity Type data exists')

            return redirect("quantity_type.all")
            # Get method
    else:
        form = QuantityTypeForm()
        quantity_types = QuantityType.objects.all()
    page = request.GET.get('page', 1)
    paginator = Paginator(quantity_types, 15)
    try:
        quantity_types = paginator.page(page)
    except PageNotAnInteger:
        quantity_types = paginator.page(1)
    except EmptyPage:
        quantity_types = paginator.page(paginator.num_pages)
    return render(request, 'quantity_type/all.html', {'quantity_types': quantity_types, "form": form})


# Currencies
@login_required(login_url=LOGIN_URL)
def all_currencies(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        method = request.POST.get("method").lower()
        if method == "post":
            form = CurrencyForm(request.POST)
            if form.is_valid():
                form.save()

templates/product/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <span>
                Add New Product
            </span>

            <a class="link" href="{% url 'product.all' %}">All Products</a>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'product.add' %}">
                {% csrf_token %}
                <div class="row">
                    {#General#}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">General information</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.name|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.location|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.identifier|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.barcode|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.weight|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">
                                        {{ form.expire|as_crispy_field }}

                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div style="display:none;">
                                            {{ form.image|as_crispy_field }}
                                        </div>
                                        <label for="formFile" class="form-label">Image</label>
                                        <input class="form-control" type="file" id="image">
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                    {# Pricing #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Pricing ($)</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.stock_price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.special|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Relations #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Relations</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.category|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.seller|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.material|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Quantity #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Quantity</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.quantity_type|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.quantity|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.extra_quantity|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.alert_if_lower_than|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Add Product</button>
            </form>
        </div>
    </div>

    <style>
        .v-application--wrap {
            min-height: unset;
        }
    </style>

    <script>
        $('document').ready(function () {
            $('#image').on('change', function () {
                var $files = $(this).get(0).files;

                if ($files.length) {
                    // Reject big files
                    if ($files[0].size > $(this).data('max-size') * 1024) {
                        console.log('Please select a smaller file');
                        return false;
                    }
                    console.log('Uploading file to Imgur..');
                    var apiUrl = 'https://api.imgur.com/3/image';
                    var apiKey = 'de1f436286677e8';
                    var settings = {
                        async: false,
                        crossDomain: true,
                        processData: false,
                        contentType: false,
                        type: 'POST',
                        url: apiUrl,
                        headers: {
                            Authorization: 'Client-ID ' + apiKey,
                            Accept: 'application/json',
                        },
                        mimeType: 'multipart/form-data',
                    };

                    var formData = new FormData();
                    formData.append('image', $files[0]);
                    settings.data = formData;
                    $.ajax(settings).done(function (response) {
                        $("#id_image").val(JSON.parse(response).data["link"])
                        alert("Image uploaded successfully")
                    });
                }
            });
        });
    </script>
{% endblock %}

templates/product/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <span>
                Add New Product
            </span>

            <a class="link" href="{% url 'product.all' %}">All Products</a>
        </div>
        <div class="card-body">
            <form method="post" action="{% url 'product.edit' product.pk %}">
                {% csrf_token %}
                <div class="row">
                    {#General#}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">General information</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.name|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.location|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.identifier|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.barcode|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.weight|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">
                                        {{ form.expire|as_crispy_field }}
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div style="display:none;">
                                            {{ form.image|as_crispy_field }}
                                        </div>
                                        <label for="formFile" class="form-label">Image</label>
                                        <input class="form-control" type="file" id="image">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Pricing #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Pricing ($)</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.stock_price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.price|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.special|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Relations #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Relations</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.category|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.seller|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.material|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {# Quantity #}
                    <div class="col-12 col-md-6 mb-4">
                        <div class="card">
                            <div class="card-header">Quantity</div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">{{ form.quantity_type|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.quantity|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.extra_quantity|as_crispy_field }}</div>
                                    <div class="col-12 col-md-6">{{ form.alert_if_lower_than|as_crispy_field }}</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-success">Update Product</button>
            </form>
        </div>
    </div>

    <style>
        .v-application--wrap {
            min-height: unset;
        }
    </style>
    <script>
        var app = new Vue({
            delimiters: ["[[", "]]"],
            el: '#dpick',
            vuetify: new Vuetify(),
            data: () => {
                return {
                    exp: new Date().toISOString().split("T")[0],
                    menu1: false
                }
            }
        })
    </script>

    <script>
        $('document').ready(function () {
            $('#image').on('change', function () {
                var $files = $(this).get(0).files;

                if ($files.length) {
                    // Reject big files
                    if ($files[0].size > $(this).data('max-size') * 1024) {
                        console.log('Please select a smaller file');
                        return false;
                    }
                    console.log('Uploading file to Imgur..');
                    var apiUrl = 'https://api.imgur.com/3/image';
                    var apiKey = 'de1f436286677e8';
                    var settings = {
                        async: false,
                        crossDomain: true,
                        processData: false,
                        contentType: false,
                        type: 'POST',
                        url: apiUrl,
                        headers: {
                            Authorization: 'Client-ID ' + apiKey,
                            Accept: 'application/json',
                        },
                        mimeType: 'multipart/form-data',
                    };

                    var formData = new FormData();
                    formData.append('image', $files[0]);
                    settings.data = formData;
                    $.ajax(settings).done(function (response) {
                        $("#id_image").val(JSON.parse(response).data["link"])
                        alert("Image uploaded successfully")
                    });
                }
            });
        });
    </script>
{% endblock %}